### ISSUE TITLE
validate workflow is broken

### ISSUE THREAD

**Issue by bluebrown** [s3-actions/s3cmd#1]
> Error : .github#L1 every step must define a `uses` or `run` key

Steps should look like this. No hyphen on the run step.

```yml
 steps:
      - name: Build dist
        run: |
```
