### ISSUE TITLE
access denied

### ISSUE THREAD

**Issue by drewkhoury** [s3-actions/s3cmd#2]
Am getting access denied when using this, even though other actions in the same main.yml can access just fine.

```
     # other action for reference
      - name: Deploy Presentation content to tmp bucket
        run: cd presentations && make deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1

      - name: Set up S3cmd cli tool
        uses: s3-actions/s3cmd@v1.1
        with:
          provider: aws # default is linode
          region: 'us-east-1'
          access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Copy presentation to main site bucket - subfolder
        run: |
          s3cmd info s3://XXX
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
```

I tried with and without the `env` vars for the run action just incase.

I get:

```
Run s3cmd info s3://XXX
  shell: /usr/bin/bash -e {0}
  env:
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
    AWS_DEFAULT_REGION: us-east-1
ERROR: Access to bucket 'XXX' was denied
ERROR: S3 error: 403 (AccessDenied): Access Denied
Error: Process completed with exit code 77.
```
