### ISSUE TITLE
Doesn't work with temporary AWS credentials?

### ISSUE THREAD

**Issue by markplewis** [s3-actions/s3cmd#20]
I'm certainly no AWS or DevOps expert, so please correct me if I'm wrong, but the `s3cmd` action doesn't seem to work with temporary AWS credentials. Here's an example of how it's supposed to work: 

https://github.com/marketplace/actions/configure-aws-credentials-action-for-github-actions#retrieving-credentials-from-step-output-assumerole-with-temporary-credentials

And here's what I'm trying to do:

```yaml
steps:
  - name: Configure AWS Credentials
    id: creds
    uses: aws-actions/configure-aws-credentials@v4
    with:
      aws-region: ca-central-1
      role-to-assume: ****
      output-credentials: true
  - name: Get caller identity
    run: aws sts get-caller-identity
    shell: bash
  - name: Set up s3cmd CLI tool
    uses: s3-actions/s3cmd@v1.9.0
    with:
      provider: aws
      region: ca-central-1
      access_key: ${{ steps.creds.outputs.aws-access-key-id }}
      secret_key: ${{ steps.creds.outputs.aws-secret-access-key }}
```

The problem is that I also need to pass `steps.creds.outputs.aws-session-token` to `s3cmd`, but the `s3-actions/s3cmd` action doesn't currently have an input for this.

Thanks!

**Comment by markplewis** [comment]
Update! I was able to get it working as follows, so I suppose this issue can be closed:

```yaml
steps:
  - name: Configure AWS Credentials
    id: creds
    uses: aws-actions/configure-aws-credentials@v4
    with:
      aws-region: ca-central-1
      role-to-assume: ****
      output-credentials: true
  - name: Get caller identity
    run: aws sts get-caller-identity
    shell: bash
  - name: Set up s3cmd CLI tool
    uses: s3-actions/s3cmd@v1.9.0
    env:
      AWS_ACCESS_KEY_ID: ${{ steps.creds.outputs.aws-access-key-id }}
      AWS_SECRET_ACCESS_KEY: ${{ steps.creds.outputs.aws-secret-access-key }}
      AWS_SESSION_TOKEN: ${{ steps.creds.outputs.aws-session-token }}
    with:
      provider: aws
      region: ca-central-1
```
